In [20]:
# -*- coding: utf-8 -*-
# Using Vertibi algorithm
from __future__ import print_function
from __future__ import division

import numpy as np

def Viterbi(A, B, PI, V, Q, obs):
    N = len(Q)
    T = len(obs)
    delta = np.array([[0] * N] * T, dtype=np.float64)
    phi = np.array([[0] * N] * T, dtype=np.int64)
    
    # 初始化
    for i in range(N):
        delta[0, i] = PI[i]*B[i][V.index(obs[0])]
        phi[0, i] = 0
#     print(delta)
#     print(phi)

    # 递归计算
    for i in range(1, T):
        for j in range(N):
            tmp = [delta[i-1, k]*A[k][j] for k in range(N)]
            delta[i,j] = max(tmp) * B[j][V.index(obs[i])]
            phi[i,j] = tmp.index(max(tmp))

    # 最终的概率及节点
#     print(delta)
    print(phi)
    P = max(delta[T-1, :])
    I = int(np.argmax(delta[T-1, :]))

    # 最优路径path
    path = [I]
    for i in reversed(range(1, T)):
        end = path[-1]
        path.append(phi[i, end])
    print(path)
    hidden_states = [Q[i] for i in reversed(path)]

    return P, hidden_states


def main():

    # 状态集合
    Q = (u'欢乐谷', u'迪士尼', u'外滩')
    # 观测集合
    V = [u'购物', u'不购物']
    # 转移概率: Q -> Q
    A = [[0.8, 0.05, 0.15],
         [0.2, 0.6, 0.2],
         [0.2, 0.3, 0.5]
        ]

    # 发射概率, Q -> V
    B = [[0.1, 0.9],
         [0.8, 0.2],
         [0.3, 0.7]
         ]

    # 初始概率
    PI = [1/3, 1/3, 1/3]

    # 观测序列
    obs = [u'不购物', u'购物', u'购物']

    P, hidden_states = Viterbi(A,B,PI,V,Q,obs)
    print(u'最大的概率为: %.5f.'%P)
    print(u'隐藏序列为：%s.'%','.join(hidden_states))

main()

[[0 0 0]
 [0 2 2]
 [0 1 2]]
[1, 1, 2]
最大的概率为: 0.02688.
隐藏序列为：外滩,迪士尼,迪士尼.
